name: FTP Deploy to Local Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build Vite project
        run: npm run build

      - name: Upload to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: 127.0.0.1
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: dist
